import { useMemo, useState } from "react";
import { Search, Trash2, UserRound, Pencil, X, Save } from "lucide-react";
import { toast } from "sonner";
import { useDeleteUserMutation, useGetUsersQuery, useUpdateUserMutation } from "../../features/users/userApiSlice";
import { useGetDepartmentsQuery } from "../../features/departments/departmentApiSlice";
import Card from "../../components/ui/Card";
import Button from "../../components/ui/Button";

const AdminUsersPage = () => {
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState(null);
  const { data, isLoading, isError } = useGetUsersQuery({ limit: 100 });
  const { data: deptData } = useGetDepartmentsQuery();
  const [deleteUser, { isLoading: deleting }] = useDeleteUserMutation();
  const [updateUser, { isLoading: updating }] = useUpdateUserMutation();
  const users = data?.data?.users || [];
  const departments = deptData?.data?.departments || [];
  const filtered = useMemo(() => users.filter((u) => `${u.firstName||""} ${u.lastName||""} ${u.email||""} ${u.role||""}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  const remove = async (id) => { if (!window.confirm("Deactivate this user? They will no longer be able to log in.")) return; try { await deleteUser(id).unwrap(); toast.success("User deactivated"); } catch (err) { toast.error(err?.data?.message || "Unable to deactivate user"); } };
  const openEdit = (u) => setEditing({ ...u, department: u.department?._id || u.department || "", isActive: u.isActive !== false });
  const saveEdit = async () => { try { await updateUser({ id: editing._id, firstName: editing.firstName, lastName: editing.lastName, phone: editing.phone||"", role: editing.role, isActive: editing.isActive, department: editing.department||undefined }).unwrap(); toast.success("User updated successfully"); setEditing(null); } catch (err) { toast.error(err?.data?.message || "Unable to update user"); } };

  return <div className="flex flex-col gap-6">
    <div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">User Management</h1><p className="mt-1 text-sm text-slate-500">Edit profiles, roles, departments and account status.</p></div>
    <Card className="overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-200 p-4 dark:border-slate-800"><Search size={18} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search users..." className="w-full bg-transparent outline-none"/></div>{isLoading?<div className="p-6 text-sm text-slate-500">Loading users…</div>:isError?<div className="p-6 text-sm text-red-500">Unable to load users.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800/60"><tr><th className="p-4">User</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{filtered.map(u=><tr key={u._id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-50 text-brand-600"><UserRound size={17}/></div><span className="font-medium">{u.firstName} {u.lastName}</span></div></td><td className="p-4 text-slate-500">{u.email}</td><td className="p-4 capitalize">{u.role}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.isActive===false?"bg-red-50 text-red-600":"bg-emerald-50 text-emerald-700"}`}>{u.isActive===false?"Inactive":"Active"}</span></td><td className="p-4 text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="secondary" onClick={()=>openEdit(u)}><Pencil size={14}/> Edit</Button><Button size="sm" variant="danger" isLoading={deleting} onClick={()=>remove(u._id)}><Trash2 size={14}/> Deactivate</Button></div></td></tr>)}{!filtered.length&&<tr><td colSpan="5" className="p-8 text-center text-slate-500">No users found.</td></tr>}</tbody></table></div>}</Card>
    {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm"><div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-600">User Profile</p><h2 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">Edit {editing.firstName} {editing.lastName}</h2></div><button onClick={()=>setEditing(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18}/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">First name<input value={editing.firstName||""} onChange={e=>setEditing({...editing,firstName:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800"/></label><label className="text-sm font-semibold">Last name<input value={editing.lastName||""} onChange={e=>setEditing({...editing,lastName:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800"/></label><label className="text-sm font-semibold">Phone<input value={editing.phone||""} onChange={e=>setEditing({...editing,phone:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800"/></label><label className="text-sm font-semibold">Role<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800"><option value="student">Student</option><option value="teacher">Teacher</option><option value="registrar">Registrar</option><option value="admin">Admin</option></select></label><label className="text-sm font-semibold sm:col-span-2">Department<select value={editing.department||""} onChange={e=>setEditing({...editing,department:e.target.value})} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800"><option value="">No department</option>{departments.map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select></label><label className="flex items-center gap-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> Account active</label></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button isLoading={updating} onClick={saveEdit}><Save size={15}/> Save Changes</Button></div></div></div>}
  </div>;
};
export default AdminUsersPage;
